name: Test workflow-dispatch
on:
  workflow_dispatch:
    inputs:
      select_environment:
        description: 'Select environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod
      image_name:
        description: 'Add image name'
        required: true
        type: string
      image_tag:
        description: 'Add image tag'
        type: string
        required: true
      acl_name:
        description: 'ACL name'
        required: true
        type: string
      

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.image_name }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The image name is  ${{ inputs.acl_name }} 
      - name: Set image name as env 
        run: echo "env_image_name=${{ inputs.image_name }}" >> $GITHUB_ENV
      - name: print the image name from env
        run: echo "Rahees your image name from env is ${{ env.env_image_name }}"
      - uses: actions/checkout@v4
      - name: execute ls command
        run: ls -ll && pwd
      - name: cat scripts/print_inputs.sh
        run: cat scripts/print_inputs.sh
      - name: Passing workflow job env to shell script
        run: |
          chmod +x scripts/print_inputs.sh
          ./scripts/print_inputs.sh