name: Test workflow-dispatch
on:
  workflow_dispatch:
    inputs:
      select_environment:
        description: 'Select environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod
      image_name:
        description: 'Add image name'
        required: true
        type: string
      image_tag:
        description: 'Add image tag'
        type: string
        required: true
      acl_name:
        description: 'ACL name'
        required: true
        type: string
      

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.image_name }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The image name is  ${{ inputs.acl_name }} 